SELECT 
	Lote AS lote_bags,
	operador,
	data_lote,
	turno,
	big_bag_utilizado,
	reutilizacao,
	peso_bruto_big_bag_1,
	diferenca_de_peso_big_bag_1,
	observacoes_big_bag_1,
	peso_bruto_big_bag_8,
	diferenca_de_peso_big_bag_8,
	observacoes_big_bag_8,
	peso_bruto_big_bag_15,
	diferenca_de_peso_big_bag_15,
	observacoes_big_bag_15,
	todos_paletes_ok AS pallet_ok,
	todos_big_bags_ok AS bag_og,
	todas_etiquetas_ok AS etiqueta_ok,
	observacoes,
	tipo_de_item,
	caminho,
	1::TEXT AS Número_bag_1,
	2::TEXT AS Número_bag_2,
	3::TEXT AS Número_bag_3,
	4::TEXT AS Número_bag_4,
	5::TEXT AS Número_bag_5,
	6::TEXT AS Número_bag_6,
	7::TEXT AS Número_bag_7,
	8::TEXT AS Número_bag_8,
	9::TEXT AS Número_bag_9,
	10::TEXT AS Número_bag_10,
	11::TEXT AS Número_bag_11,
	12::TEXT AS Número_bag_12,
	13::TEXT AS Número_bag_13,
	14::TEXT AS Número_bag_14,
	15::TEXT AS Número_bag_15,
	16::TEXT AS Número_bag_16,
	17::TEXT AS Número_bag_17,
	18::TEXT AS Número_bag_18,
	19::TEXT AS Número_bag_19,
	20::TEXT AS Número_bag_20,
	SPLIT_PART(peso_liquido,'§',1)::INTEGER AS BAG1, 
	SPLIT_PART(peso_liquido,'§',2)::INTEGER AS BAG2,
	SPLIT_PART(peso_liquido,'§',3)::INTEGER AS BAG3,
	SPLIT_PART(peso_liquido,'§',4)::INTEGER AS BAG4,
	SPLIT_PART(peso_liquido,'§',5)::INTEGER AS BAG5,
	SPLIT_PART(peso_liquido,'§',6)::INTEGER AS BAG6,
	SPLIT_PART(peso_liquido,'§',7)::INTEGER AS BAG7,
	SPLIT_PART(peso_liquido,'§',8)::INTEGER AS BAG8,
	SPLIT_PART(peso_liquido,'§',9)::INTEGER AS BAG9,
	SPLIT_PART(peso_liquido,'§',10)::INTEGER AS BAG10,
	SPLIT_PART(peso_liquido,'§',11)::INTEGER AS BAG11,
	SPLIT_PART(peso_liquido,'§',12)::INTEGER AS BAG12,
	SPLIT_PART(peso_liquido,'§',13)::INTEGER AS BAG13,
	SPLIT_PART(peso_liquido,'§',14)::INTEGER AS BAG14,
	SPLIT_PART(peso_liquido,'§',15)::INTEGER AS BAG15,
	SPLIT_PART(peso_liquido,'§',16)::INTEGER AS BAG16,
	CASE WHEN(SPLIT_PART(peso_liquido,'§',17)='') THEN '0' ELSE SPLIT_PART(peso_liquido,'§',17) END ::INTEGER AS BAG17,
	CASE WHEN(SPLIT_PART(peso_liquido,'§',18)='') THEN '0' ELSE SPLIT_PART(peso_liquido,'§',18) END ::INTEGER AS BAG18,
	CASE WHEN(SPLIT_PART(peso_liquido,'§',19)='') THEN '0' ELSE SPLIT_PART(peso_liquido,'§',19) END ::INTEGER AS BAG19,
	CASE WHEN(SPLIT_PART(peso_liquido,'§',20)='') THEN '0' ELSE SPLIT_PART(peso_liquido,'§',20) END ::INTEGER AS BAG20,
	SPLIT_PART(tara,'§',1)::INTEGER AS TARA_BAG1, 
	SPLIT_PART(tara,'§',2)::INTEGER AS TARA_BAG2,
	SPLIT_PART(tara,'§',3)::INTEGER AS TARA_BAG3,
	SPLIT_PART(tara,'§',4)::INTEGER AS TARA_BAG4,
	SPLIT_PART(tara,'§',5)::INTEGER AS TARA_BAG5,
	SPLIT_PART(tara,'§',6)::INTEGER AS TARA_BAG6,
	SPLIT_PART(tara,'§',7)::INTEGER AS TARA_BAG7,
	SPLIT_PART(tara,'§',8)::INTEGER AS TARA_BAG8,
	SPLIT_PART(tara,'§',9)::INTEGER AS TARA_BAG9,
	SPLIT_PART(tara,'§',10)::INTEGER AS TARA_BAG10,
	SPLIT_PART(tara,'§',11)::INTEGER AS TARA_BAG11,
	SPLIT_PART(tara,'§',12)::INTEGER AS TARA_BAG12,
	SPLIT_PART(tara,'§',13)::INTEGER AS TARA_BAG13,
	SPLIT_PART(tara,'§',14)::INTEGER AS TARA_BAG14,
	SPLIT_PART(tara,'§',15)::INTEGER AS TARA_BAG15,
	SPLIT_PART(tara,'§',16)::INTEGER AS TARA_BAG16,
	SPLIT_PART(tara,'§',17)::INTEGER AS TARA_BAG17,
	SPLIT_PART(tara,'§',18)::INTEGER AS TARA_BAG18,
	CASE WHEN(SPLIT_PART(tara,'§',19)='') THEN '0' ELSE SPLIT_PART(tara,'§',19) END ::INTEGER AS TARA_BAG19,
	CASE WHEN(SPLIT_PART(tara,'§',20)='') THEN '0' ELSE SPLIT_PART(tara,'§',20) END ::INTEGER AS TARA_BAG20,
	SPLIT_PART(numero_lacre,'§',1) AS numero_lacre_BAG1, 
	SPLIT_PART(numero_lacre,'§',2) AS numero_lacre_BAG2,
	SPLIT_PART(numero_lacre,'§',3) AS numero_lacre_BAG3,
	SPLIT_PART(numero_lacre,'§',4) AS numero_lacre_BAG4,
	SPLIT_PART(numero_lacre,'§',5) AS numero_lacre_BAG5,
	SPLIT_PART(numero_lacre,'§',6) AS numero_lacre_BAG6,
	SPLIT_PART(numero_lacre,'§',7) AS numero_lacre_BAG7,
	SPLIT_PART(numero_lacre,'§',8) AS numero_lacre_BAG8,
	SPLIT_PART(numero_lacre,'§',9) AS numero_lacre_BAG9,
	SPLIT_PART(numero_lacre,'§',10) AS numero_lacre_BAG10,
	SPLIT_PART(numero_lacre,'§',11) AS numero_lacre_BAG11,
	SPLIT_PART(numero_lacre,'§',12) AS numero_lacre_BAG12,
	SPLIT_PART(numero_lacre,'§',13) AS numero_lacre_BAG13,
	SPLIT_PART(numero_lacre,'§',14) AS numero_lacre_BAG14,
	SPLIT_PART(numero_lacre,'§',15) AS numero_lacre_BAG15,
	SPLIT_PART(numero_lacre,'§',16) AS numero_lacre_BAG16,
	SPLIT_PART(numero_lacre,'§',17) AS numero_lacre_BAG17,
	SPLIT_PART(numero_lacre,'§',18) AS numero_lacre_BAG18,
	SPLIT_PART(numero_lacre,'§',19) AS numero_lacre_BAG19,
	SPLIT_PART(numero_lacre,'§',20) AS numero_lacre_BAG20

FROM bags_sharepoint;
